name: resumesux_application
description: Contracts and usecases for ResumesUX clean architecture
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  fpdart: ^1.2.0
  resumesux_domain:
    git:
      url: https://github.com/staylorx/resumesux_domain

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
  mocktail: ^1.0.4
